dist: trusty
sudo: false
language: java
jdk:
  - oraclejdk8
before_install:
  - ulimit -c unlimited -S

before_script: cd myserver

script:
  - ./mvnw test -B
  - ./mvnw site -pl docs -B

cache:
  directories:
    - $HOME/.m2